# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vlg', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
